---
title: "Connecting to Data"
vignette: >
  %\VignetteIndexEntry{connect_to_data}
  %\VignetteEngine{quarto::html}
  %\VignetteEncoding{UTF-8}
knitr:
  opts_chunk:
    collapse: true
    comment: '#>'
---



Mighty in itself does not read any data, but the generated programs will
need to connect to a data source to be able to execute. Thus, the programs
will use the
[`connector`](https://github.com/NovoNordisk-OpenSource/connector/tree/main?tab=readme-ov-file#readme)
package to connect to study data.

The `path_connector_config` argument to `generate_adam_code()` controls which
directory path gets embedded in the generated programs for locating
`_connector.yml`. Mighty does not read `_connector.yml` itself — it only
embeds the path into the generated code. The file is read later when the
generated program runs. The value can be a literal directory path or an
`!expr`-prefixed R expression for runtime evaluation (e.g.,
`!expr here::here()`).

An example of a generated program can be seen below, where the `cnt` object is

*   created by reading `_connector.yml` from the directory specified by
    `path_connector_config`,
*   used to read `dm` and `dm_vaccine`, and finally
*   save the created `ADSL` data set.


```r
# LOAD all external datasets needed ------------------------------------------------

cnt <- connector::connect(config = file.path(".", "_connector.yml"))

dm <- cnt$sdtm$read_cnt("dm") |> dplyr::select(ACTARM, AGE, AGEU, ARM, COUNTRY, DOMAIN, DTHFL, RACE, SEX, STUDYID, USUBJID)

dm_vaccine <- cnt$sdtm$read_cnt("dm_vaccine") |> dplyr::select(ACTARM, AGE, AGEU, ARM, COUNTRY, DOMAIN, DTHFL, RACE, SEX, STUDYID, USUBJID)

### Generated ADaM program code (removed for simplicity)

# Save ADSL ------------------------------------------------

cnt$adam$write_cnt(ADSL, "ADSL.parquet", overwrite = TRUE)

# Remove input tables
rm(list = c("dm", "dm_vaccine"))
```
