#' Remove last two lines of generated programs to avoid writing ADaM dataset
#'
#' @description
#' When generated programs are executed, the final step is to execute code
#' generated by the `mighty_write_data` template. Here, the
#' last two statements are:
#'   `# Save ADaM table`
#'   `cnt$adam$write_cnt(DOMAIN, tolower("DOMAIN.parquet"), overwrite = TRUE)`
#' This wil save a data set. However, on Windows, if the file is written for
#' the second time, this will fail with error
#' ```
#' [Windows error 1224] The requested operation cannot be performed on a file
#' with a user-mapped section open.
#' ```
#' To avoid this, this function is used to strip the last two lines of the
#' generated program, such that the program will never write this data set.
#'
#' @param program Generated program from generate_adam_code() (either
#' programs or executable_programs) that should avoid storing a data set
#'
#' @returns On Windows, an adjusted program where the last two lines from the
#' generated program is removed. Otherwise the program itself is returned.
#'
#' @note Assumption: Programs are generated using the
#'   `mighty_write_data`
#' template as the final step. The last two lines generated by the template,
#' should be removed.
#'
#' @noRd
remove_connector_write_step <- function(program) {
  if (.Platform$OS.type == "windows") {
    program_lines <- strsplit(program, "\n")[[1]]
    program_lines <- program_lines[1:(length(program_lines) - 2)]
    return(paste(program_lines, collapse = "\n"))
  }
  program
}
