test_that("Complex test with multiple domains and column/row operations", {
  # SETUP -------------------------------------------------------------------

  path_ui_data <- c(
    test_path("fixtures", "complex_adsl.yml"),
    test_path("fixtures", "complex_adlb.yml")
  )
  path_ui_data_rendered <- setup_yml_file_for_testing(
    path_ui_data,
    environment()
  )

  path_trial_metadata <- test_path("fixtures", "trial_metadata_0001.yml")
  path_trial <- withr::local_tempdir()

  setup_testdata(
    testdata = "pharmaverse",
    test_data_path = path_trial,
    sdtm_domains = c("dm", "dm_vaccine", "lb", "sv")
  )
  standards_lib <- "mighy.standards"

  # ACT ---------------------------------------------------------------------

  actual <- generate_adam_code(
    path_ui_data = path_ui_data_rendered,
    standards_lib = standards_lib,
    path_trial_metadata = path_trial_metadata,
    path_trial = path_trial,
    check_cross_domain_adam_dependencies = TRUE
  )

  # EXPECT ------------------------------------------------------------------

  actual$data_model$actions |>
    names() |>
    expect_setequal(
      c(
        "code_id",
        "depend_cols",
        "depend_rows",
        "domain",
        "node_id",
        "outputs",
        "parameters",
        "type"
      )
    )
  write_adam_programs(
    dir = path_trial,
    programs = actual$programs,
    style = TRUE
  )
  x <- list.files(path_trial, pattern = ".R", full.names = TRUE)

  programs <- x |> lapply(readLines)
  names(programs) <- basename(x)

  path_comp <- paste0("-", test_path(), "/fixtures/components/")

  # Check program 1: ADSL part 1
  expect_section_order(
    "ADSL-PLANNED_ARM",
    paste0("ADSL-ARM_GRP1", path_comp, "arm_group_01.R"),
    programs[["1_ADSL.R"]]
  )
  expect_section_order(
    "ADSL-PLANNED_ARM",
    paste0("ADSL-NEW_ARM", path_comp, "arm_01.R"),
    programs[["1_ADSL.R"]]
  )
  expect_section_order(
    "ADSL-PLANNED_ARM",
    paste0("ADSL-ARM_MATCH", path_comp, "arm_match_01.R"),
    programs[["1_ADSL.R"]]
  )
  expect_section_order(
    paste0("ADSL-ARM_GRP1", path_comp, "arm_group_01.R"),
    paste0("ADSL-ARM_CAT1", path_comp, "arm_category_01"),
    programs[["1_ADSL.R"]]
  )
  expect_section_order(
    paste0("ADSL-AGE2", path_comp, "age_crop_01.R"),
    paste0("ADSL-AGE_DIFF1", path_comp, "age_diff_01.R"),
    programs[["1_ADSL.R"]]
  )
  expect_section_order(
    c(
      "ADSL-PLANNED_ARM",
      paste0("ADSL-AGE_DIFF1", path_comp, "age_diff_01.R")
    ),
    paste0("ADSL-AGE_DIFF2", path_comp, "age_diff_02.R"),
    programs[["1_ADSL.R"]]
  )
  expect_section_order(
    c(
      "ADSL-PLANNED_ARM",
      paste0("ADSL-AGE_DIFF1", path_comp, "age_diff_01.R")
    ),
    paste0("ADSL-NEWFL01-NEWREA01", path_comp, "newfl_01.R"),
    programs[["1_ADSL.R"]]
  )
  expect_section_order(
    paste0("ADSL-AGE2", path_comp, "age_crop_01.R"),
    paste0("ADSL-AGE_GRP1", path_comp, "age_group_01.R"),
    programs[["1_ADSL.R"]]
  )

  # Check ADSL table generated by program 1
  
  x[[1]] |> source()
  setcolorder(ADSL, sort(names(ADSL)))
  ADSL |> expect_snapshot_value(style = "json2", variant = "adsl_1")

  # Check program 2: ADLB
  
  expect_section_order(
    c(
      "ADLB-AVAL-_col_mutate",
      paste0("ADLB-LBTEST", path_comp, "new_lbtest_01.R")
    ),
    paste0("ADLB-AVAL_GRP", path_comp, "aval_grp_01.R"),
    programs[["2_ADLB.R"]]
  )
  expect_section_order(
    paste0("ADLB-AVAL", path_comp, "new_aval_01.R"),
    paste0("ADLB-LBTEST", path_comp, "lbtest_01.R"),
    programs[["2_ADLB.R"]]
  )
  expect_section_order(
    c(
      paste0("ADLB-LBTEST", path_comp, "new_lbtest_01.R"),
      paste0("ADLB-AVAL_GRP", path_comp, "aval_grp_01.R")
    ),
    paste0("ADLB-AVAL_GRP2", path_comp, "aval_grp_02.R"),
    programs[["2_ADLB.R"]]
  )
  expect_section_order(
    "ADLB-AVAL-_col_mutate",
    paste0("ADLB-AVAL", path_comp, "new_aval_01.R"),
    programs[["2_ADLB.R"]]
  )
  expect_section_order(
    "ADLB-AVAL-_col_mutate",
    paste0("ADLB-AVAL", path_comp, "new_aval_03.R"),
    programs[["2_ADLB.R"]]
  )
  expect_section_order(
    c("ADLB-AVAL-_col_mutate", "ADLB-AVALC-_col_mutate"),
    paste0("ADLB-AVAL", path_comp, "new_aval_04.R"),
    programs[["2_ADLB.R"]]
  )
  expect_section_order(
    paste0("ADLB-LBTEST", path_comp, "lbtest_01.R"),
    paste0("ADLB-LBTEST", path_comp, "new_lbtest_01.R"),
    programs[["2_ADLB.R"]]
  )
  expect_section_order(
    c(
      "ADLB-AVALC-_col_mutate",
      paste0("ADLB-LBTEST", path_comp, "lbtest_01.R")
    ),
    paste0(
      "ADLB-LBTEST-AVALC-",
      test_path(),
      "/fixtures/components/new_lbtest_02.R"
    ),
    programs[["2_ADLB.R"]]
  )
  expect_section_order(
    paste0(
      "ADLB-LBTEST-",
      test_path(),
      "/fixtures/components/new_lbtest_01.R"
    ),
    paste0(
      "ADLB-LBTEST-",
      test_path(),
      "/fixtures/components/new_lbtest_04.R"
    ),
    programs[["2_ADLB.R"]]
  )
  expect_section_order(
    c(
      paste0("ADLB-LBTEST", path_comp, "new_lbtest_01.R"),
      paste0("ADLB-LBTEST", path_comp, "new_lbtest_01.R")
    ),
    paste0("ADLB-LBTEST", path_comp, "new_lbtest_05.R"),
    programs[["2_ADLB.R"]]
  )
  expect_section_order(
    c(
      paste0("ADLB-LBTEST", path_comp, "lbtest_01.R"),
      paste0("ADLB-LBTEST", path_comp, "new_lbtest_01.R")
    ),
    paste0(
      "ADLB-LBTEST-",
      test_path(),
      "/fixtures/components/new_lbtest_03.R"
    ),
    programs[["2_ADLB.R"]]
  )
  expect_section_order(
    c(
      "ADLB-AVAL-_col_mutate",
      paste0("ADLB-AVAL", path_comp, "new_aval_01.R")
    ),
    paste0("ADLB-AVAL", path_comp, "new_aval_02.R"),
    programs[["2_ADLB.R"]]
  )
  expect_section_order(
    paste0("ADLB-VISITNUM", path_comp, "new_visitnum_01.R"),
    paste0("ADLB-VISITNUM", path_comp, "new_visitnum_02.R"),
    programs[["2_ADLB.R"]]
  )
  expect_section_order(
    paste0("ADLB-LBTEST", path_comp, "lbtest_01.R"),
    paste0("ADLB-LBTEST", path_comp, "new_lbtest_07.R"),
    programs[["2_ADLB.R"]]
  )

  expect_section_order(
    paste0("ADLB-LBTEST", path_comp, "lbtest_01.R"),
    paste0("ADLB-LBTEST", path_comp, "new_lbtest_08.R"),
    programs[["2_ADLB.R"]]
  )

  # Check ADLB table generated by program 2
  x[[2]] |> source()
  setDT(ADLB)
  setcolorder(ADLB, sort(names(ADLB)))
  data.table::setorder(ADLB, USUBJID, VISITNUM, LBSEQ, AVAL)
  attr(ADLB, "row.names") <- NULL
  ADLB |>
    data.table::setDF() |>
    expect_snapshot_value(style = "json2", variant = "adlb_1_ordered")

  # Check program 3: ADSL part 2
  expect_section_order(
    paste0("ADSL-NEWFL02", path_comp, "newfl_02.R"),
    paste0("ADSL-NEWFL03-NEWREA03", path_comp, "newfl_03.R"),
    programs[["3_ADSL.R"]]
  )

  # Check ADSL table generated by program 3
  x[[3]] |> source()
  setDT(ADSL)
  setcolorder(ADSL, sort(names(ADSL)))
  data.table::setorder(ADSL, USUBJID)
  attr(ADSL, "row.names") <- NULL

  ADSL |>
    data.table::setDF() |>
    expect_snapshot_value(style = "json2", variant = "adsl_2")

  # # Check edges
  # actual$edges |>
  #   data.table::setorder(node_id, parent_node) |>
  #   as.data.frame() |>
  #   expect_snapshot_value(style = "json2", variant = "edges")
})
