test_that("Complex test w/ missing dm_vaccine.SEX", {
  # SETUP -------------------------------------------------------------------

  path_ui_data <- c(
    test_path("fixtures", "complex_adsl.yml"),
    test_path("fixtures", "complex_adlb.yml")
  )
  path_ui_data_rendered <- setup_yml_file_for_testing(
    path_ui_data,
    environment()
  )

  path_trial_metadata <- test_path("fixtures", "trial_metadata_0001.yml")
  path_trial <- withr::local_tempdir()

  setup_testdata(
    testdata = "pharmaverse",
    test_data_path = path_trial,
    sdtm_domains = c("dm", "dm_vaccine", "lb", "sv"),
    remove_cols = data.table(domain = c("dm_vaccine"), columns = c("SEX"))
  )
  cnt <- connector::connect(file.path(path_trial, "_connector.yml"))
  standards_lib <- "mighy.standards"

  # ACT ---------------------------------------------------------------------

  actual <- generate_adam_code(
    path_ui_data = path_ui_data_rendered,
    standards_lib = standards_lib,
    path_trial_metadata = path_trial_metadata,
    path_trial = path_trial,
    check_cross_domain_adam_dependencies = TRUE,
    data_context = data_context$new(cnt)
  )
  # EXPECT ------------------------------------------------------------------

  # Filter cannot be applied to program 2 (ADLB) because ADSL is missing
  # column SEX
  ea <- actual$executable_program_sequence

  # Check that only 1 action cannot be executed
  expect_equal(nrow(ea[can_execute == FALSE]), 1)

  # Check read_data actions
  read_actions <- ea[type == "read_data"]
  expect_true(all(read_actions$can_execute))
  expect_true(all(grepl(
    "Code can be executed but the following columns are not found in source data:",
    read_actions[program_id %in% 1:2]$lineage
  )))
  expect_true(all(grepl(
    "sdtm.dm_vaccine.SEX",
    read_actions[program_id == 1]$lineage
  )))
  expect_true(all(grepl(
    "adam.ADSL.SEX",
    read_actions[program_id == 2]$lineage
  )))

  # Check filter_domain actions
  filter_actions <- ea[type == "filter_domain"]
  expect_equal(filter_actions$domain, c("ADSL", "ADLB"))
  expect_equal(filter_actions$can_execute, c(TRUE, FALSE))
  expect_equal(filter_actions[can_execute == FALSE]$rank, 2)
  expect_equal(filter_actions[can_execute == FALSE]$program_id, 2)

  # Write programs
  write_adam_programs(
    dir = path_trial,
    programs = actual$executable_programs,
    style = TRUE
  )
  x <- list.files(path_trial, pattern = ".R", full.names = TRUE)

  # Check ADSL table generated by program 1
  expect_no_error(x[[1]] |> source())
  expect_false("SEX" %in% names(ADSL))

  cols_adsl1 <- c(
    "ACTARM",
    "AGE",
    "AGEU",
    "ARM",
    "COUNTRY",
    "DOMAIN",
    "DTHFL",
    "RACE",
    "STUDYID",
    "USUBJID",
    "AGE2",
    "AGE_DIFF1",
    "AGE_GRP1",
    "RACE_COUNTRY",
    "PLANNED_ARM",
    "AGE_DIFF2",
    "ARM_GRP1",
    "ARM_CAT1",
    "ARM_MATCH",
    "NEWFL01",
    "NEWREA01",
    "NEW_ARM"
  )
  expect_setequal(names(ADSL), cols_adsl1)

  # Check ADLB table generated by program 2
  expect_no_error(x[[2]] |> source())
  expect_setequal(
    names(ADLB),
    c(
      "USUBJID",
      "VISITNUM",
      "ARM",
      "RACE_COUNTRY",
      "AVAL",
      "AVALC",
      "STUDYID",
      "LBSEQ",
      "LBSTRESN",
      "LBSTRESC",
      "DOMAIN",
      "LBTEST",
      "AVAL_GRP",
      "AVAL_GRP2"
    )
  )

  # Check ADSL table generated by program 3
  expect_no_error(x[[3]] |> source())
  expect_setequal(
    names(ADSL),
    c(cols_adsl1, "MIN_AVAL", "NEWFL02", "NEWFL03", "NEWREA03")
  )

  # Check programs that are based on the specs (without taking missing
  # data into consideration) will fail due to missing dm_vaccine.SEX
  write_adam_programs(
    dir = path_trial,
    programs = actual$programs,
    style = TRUE
  )

  # Check ADSL program 1 fails
  expect_error(x[[1]] |> source())
  # Check ADLB program 2 fails
  expect_error(x[[2]] |> source())
  # Check ADSL program 3 fails
  expect_error(x[[3]] |> source())
})

test_that("Complex test w/ missing dm_vaccine.AGE and dm.SEX", {
  # SETUP -------------------------------------------------------------------

  path_ui_data <- c(
    test_path("fixtures", "complex_adsl.yml"),
    test_path("fixtures", "complex_adlb.yml")
  )
  path_ui_data_rendered <- setup_yml_file_for_testing(
    path_ui_data,
    environment()
  )

  path_trial_metadata <- test_path("fixtures", "trial_metadata_0001.yml")
  path_trial <- withr::local_tempdir()

  setup_testdata(
    testdata = "pharmaverse",
    test_data_path = path_trial,
    sdtm_domains = c("dm", "dm_vaccine", "lb", "sv"),
    remove_cols = data.table(
      domain = c("dm_vaccine", "dm"),
      columns = c("AGE", "SEX")
    )
  )
  cnt <- connector::connect(file.path(path_trial, "_connector.yml"))
  standards_lib <- "mighy.standards"

  # ACT ---------------------------------------------------------------------

  actual <- generate_adam_code(
    path_ui_data = path_ui_data_rendered,
    standards_lib = standards_lib,
    path_trial_metadata = path_trial_metadata,
    path_trial = path_trial,
    check_cross_domain_adam_dependencies = TRUE,
    data_context = data_context$new(cnt)
  )

  # EXPECT ------------------------------------------------------------------

  # ea = executable actions
  ea <- actual$executable_program_sequence

  # Check that 7 actions cannot be executed
  expect_equal(nrow(ea[can_execute == FALSE]), 7)

  # Check read_data actions
  read_actions <- ea[type == "read_data"]
  expect_true(all(read_actions$can_execute))
  expect_true(all(grepl(
    "Code can be executed but the following columns are not found in source data:",
    read_actions[program_id %in% 1:3]$lineage
  )))
  expect_true(all(grepl(
    "sdtm.dm.SEX, sdtm.dm_vaccine.AGE",
    read_actions[program_id == 1]$lineage
  )))
  expect_true(all(grepl(
    "adam.ADSL.SEX",
    read_actions[program_id == 2]$lineage
  )))
  expect_true(all(grepl(
    "adam.ADSL.NEWFL01",
    read_actions[program_id == 3]$lineage
  )))

  # Check filter_domain actions
  filter_actions <- ea[type == "filter_domain"]
  expect_equal(filter_actions$domain, c("ADSL", "ADLB"))
  expect_equal(filter_actions$can_execute, c(TRUE, FALSE))
  expect_equal(filter_actions[can_execute == FALSE]$rank, 2)
  expect_equal(filter_actions[can_execute == FALSE]$program_id, 2)

  # Check remaining actions affected by the missing columns
  nodes_cannot_execute <- c(
    "ADSL-AGE2",
    "ADSL-AGE_DIFF1",
    "ADSL-AGE_GRP1",
    "ADSL-NEWFL01-NEWREA01",
    "ADSL-NEWFL03-NEWREA03"
  )
  expect_true(all(grepl(
    "Cannot execute code that is depending on:",
    ea[node_id %in% nodes_cannot_execute]$lineage
  )))

  # Check removed_outputs and lineage of actions
  # The following nodes contain messages similar to
  #   Cannot execute code that is depending on:
  #   adam.ADSL.col1, adam.ADSL.col2
  #   The following columns cannot be created:
  #   adam.ADSL.col3
  node <-  ea[node_id == "ADSL-AGE2"]
  expect_true(
    grep("adam.ADSL.AGE", node$lineage) &&
      grep("adam.ADSL.AGE2", node$lineage)
  )
  expect_setequal(node$removed_outputs[[1]], c("ADSL.AGE2"))

  node <-  ea[node_id == "ADSL-AGE_DIFF1"]
  expect_true(
    grep("adam.ADSL.AGE, adam.ADSL.AGE2", node$lineage) &&
      grep("adam.ADSL.AGE_DIFF1", node$lineage)
  )
  expect_setequal(node$removed_outputs[[1]], c("ADSL.AGE_DIFF1"))

  node <-  ea[node_id == "ADSL-AGE_GRP1"]
  expect_true(
    grep("adam.ADSL.AGE2", node$lineage) &&
      grep("adam.ADSL.AGE_GRP1", node$lineage)
  )
  expect_setequal(node$removed_outputs[[1]], c("ADSL.AGE_GRP1"))

  node <-  ea[node_id == "ADSL-AGE_DIFF2"]
  expect_true(
    grep("adam.ADSL.AGE_DIFF1", node$lineage) &&
      grep("adam.ADSL.AGE_DIFF2", node$lineage)
  )
  expect_setequal(node$removed_outputs[[1]], c("ADSL.AGE_DIFF2"))

  node <-  ea[node_id == "ADSL-NEWFL01-NEWREA01"]
  expect_true(
    grep("adam.ADSL.AGE_DIFF1", node$lineage) &&
      grep("adam.ADSL.NEWFL01, adam.ADSL.NEWREA01", node$lineage)
  )
  expect_setequal(node$removed_outputs[[1]], c("ADSL.NEWFL01", "ADSL.NEWREA01"))

  node <-  ea[node_id == "ADSL-NEWFL03-NEWREA03"]
  expect_true(
    grep("adam.ADSL.NEWFL01", node$lineage) &&
      grep("adam.ADSL.NEWFL03, adam.ADSL.NEWREA03", node$lineage)
  )
  expect_setequal(node$removed_outputs[[1]], c("ADSL.NEWFL03", "ADSL.NEWREA03"))

  # Write programs
  write_adam_programs(
    dir = path_trial,
    programs = actual$executable_programs,
    style = TRUE
  )
  x <- list.files(path_trial, pattern = ".R", full.names = TRUE)

  # Check ADSL table generated by program 1
  cols_adsl1 <- c(
    "USUBJID",
    "DOMAIN",
    "AGEU",
    "ARM",
    "DTHFL",
    "STUDYID",
    "ACTARM",
    "COUNTRY",
    "RACE",
    "RACE_COUNTRY",
    "PLANNED_ARM",
    "NEW_ARM",
    "ARM_GRP1",
    "ARM_CAT1",
    "ARM_MATCH"
  )
  expect_no_error(x[[1]] |> source())
  expect_setequal(names(ADSL), cols_adsl1)

  # Check ADLB table generated by program 2
  expect_no_error(x[[2]] |> source())
  expect_setequal(
    names(ADLB),
    c(
      "USUBJID",
      "VISITNUM",
      "ARM",
      "RACE_COUNTRY",
      "AVAL",
      "AVALC",
      "STUDYID",
      "LBSEQ",
      "LBSTRESN",
      "LBSTRESC",
      "DOMAIN",
      "LBTEST",
      "AVAL_GRP",
      "AVAL_GRP2"
    )
  )

  # Check ADSL table generated by program 3
  expect_no_error(x[[3]] |> source())
  expect_setequal(
    names(ADSL),
    c(cols_adsl1, "ARM_MATCH", "MIN_AVAL", "NEWFL02")
  )

  # Check programs that are based on the specs (without taking missing
  # data into consideration) will fail due to missing dm_vaccine.AGE
  # and dm.SEX
  write_adam_programs(
    dir = path_trial,
    programs = actual$programs,
    style = TRUE
  )

  # Check ADSL (program 1) will fail
  expect_error(x[[1]] |> source())
  # Check ADLB (program 2) will fail
  expect_error(x[[2]] |> source())
  # Check ADSL (program 3) will fail
  expect_error(x[[3]] |> source())
})

test_that("Complex test w/ missing lb.LBSTRESN", {
  # SETUP -------------------------------------------------------------------
  path_ui_data <- c(
    test_path("fixtures", "complex_adsl.yml"),
    test_path("fixtures", "complex_adlb.yml")
  )
  path_ui_data_rendered <- setup_yml_file_for_testing(
    path_ui_data,
    environment()
  )

  path_trial_metadata <- test_path("fixtures", "trial_metadata_0001.yml")
  path_trial <- withr::local_tempdir()

  setup_testdata(
    testdata = "pharmaverse",
    test_data_path = path_trial,
    sdtm_domains = c("dm", "dm_vaccine", "lb", "sv"),
    remove_cols = data.table(domain = c("lb"), columns = c("LBSTRESN"))
  )
  cnt <- connector::connect(file.path(path_trial, "_connector.yml"))
  standards_lib <- "mighy.standards"

  # ACT ---------------------------------------------------------------------

  actual <- generate_adam_code(
    path_ui_data = path_ui_data_rendered,
    standards_lib = standards_lib,
    path_trial_metadata = path_trial_metadata,
    path_trial = path_trial,
    check_cross_domain_adam_dependencies = TRUE,
    data_context = data_context$new(cnt)
  )

  # EXPECT ------------------------------------------------------------------

  # ea means executable_actions
  ea <- actual$executable_program_sequence
  action_lineage <- ea$lineage

  # Check that 20 actions cannot be executed
  expect_equal(nrow(ea[can_execute == FALSE]), 20)

  # Check read_data actions
  read_actions <- ea[type == "read_data"]
  expect_true(all(read_actions$can_execute))
  expect_true(all(grepl(
    "Code can be executed but the following columns are not found in source data:",
    read_actions[program_id %in% c("2", "3")]$lineage
  )))
  expect_true(all(grepl(
    "sdtm.lb.LBSTRESN",
    read_actions[program_id %in% c("2")]$lineage
  )))
  expect_true(all(grepl(
    "adam.ADLB.AVAL, adam.ADLB.LBTEST",
    read_actions[program_id %in% c("3")]$lineage
  )))

  # Check filter_domain actions
  filter_actions <- ea[type == "filter_domain"]
  expect_equal(nrow(filter_actions[can_execute == FALSE]), 0)
  expect_true(all(grepl(
    "Cannot execute code that is depending on:",
    action_lineage[c(21:33, 35:38, 43:45)]
  )))

  # Check lineage of actions
  expect_true(grepl("adam.ADLB.LBSTRESN", action_lineage[21]))
  expect_true(grepl("adam.ADLB.AVAL", action_lineage[21]))
  expect_true(grepl("adam.ADLB.AVAL", action_lineage[22]))
  expect_true(grepl("adam.ADLB.AVAL", action_lineage[23]))
  expect_true(grepl("adam.ADLB.LBTEST", action_lineage[23]))
  expect_true(grepl("adam.ADLB.LBTEST", action_lineage[24]))
  expect_true(grepl("adam.ADLB.AVAL", action_lineage[25]))
  expect_true(grepl("adam.ADLB.AVAL_GRP", action_lineage[25]))
  expect_true(grepl("adam.ADLB.AVAL_GRP", action_lineage[26]))
  expect_true(grepl("adam.ADLB.AVAL_GRP2", action_lineage[26]))
  expect_true(grepl("adam.ADLB.LBTEST", action_lineage[27]))
  expect_true(grepl("adam.ADLB.LBTEST", action_lineage[28]))
  expect_true(grepl("adam.ADLB.AVAL", action_lineage[28]))
  expect_true(grepl("adam.ADLB.LBTEST", action_lineage[29]))
  expect_true(grepl("adam.ADLB.LBTEST", action_lineage[30]))
  expect_true(grepl("adam.ADLB.LBTEST", action_lineage[31]))
  expect_true(grepl("adam.ADLB.AVAL", action_lineage[32]))
  expect_true(grepl("adam.ADLB.AVAL", action_lineage[33]))
  expect_true(grepl("adam.ADLB.AVAL", action_lineage[35]))
  expect_true(grepl("adam.ADLB.AVALC", action_lineage[36]))
  expect_true(grepl("adam.ADLB.LBTEST", action_lineage[36]))
  expect_true(grepl("adam.ADLB.LBTEST", action_lineage[37]))
  expect_true(grepl("adam.ADLB.LBTEST", action_lineage[38]))
  expect_true(grepl("adam.ADLB.AVAL", action_lineage[43]))
  expect_true(grepl("adam.ADSL.MIN_AVAL", action_lineage[43]))
  expect_true(grepl("adam.ADLB.LBTEST", action_lineage[44]))
  expect_true(grepl("adam.ADSL.NEWFL02", action_lineage[44]))
  expect_true(grepl("adam.ADSL.NEWFL02", action_lineage[45]))
  expect_true(grepl("adam.ADSL.NEWFL03", action_lineage[45]))
  expect_true(grepl("adam.ADSL.NEWREA03", action_lineage[45]))

  write_adam_programs(
    dir = path_trial,
    programs = actual$executable_programs,
    style = TRUE
  )
  x <- list.files(path_trial, pattern = ".R", full.names = TRUE)

  # Check ADSL table generated by program 1
  cols_adsl1 <- c(
    "USUBJID",
    "DOMAIN",
    "AGEU",
    "ARM",
    "DTHFL",
    "STUDYID",
    "ACTARM",
    "COUNTRY",
    "RACE",
    "RACE_COUNTRY",
    "PLANNED_ARM",
    "NEW_ARM",
    "ARM_GRP1",
    "ARM_CAT1",
    "ARM_MATCH",
    "SEX",
    "AGE",
    "AGE2",
    "AGE_DIFF1",
    "AGE_DIFF2",
    "NEWFL01",
    "NEWREA01",
    "AGE_GRP1"
  )
  expect_no_error(x[[1]] |> source())
  expect_setequal(names(ADSL), cols_adsl1)

  # Check ADLB table generated by program 2
  expect_no_error(x[[2]] |> source())
  expect_setequal(
    names(ADLB),
    c(
      "USUBJID",
      "VISITNUM",
      "ARM",
      "RACE_COUNTRY",
      "AVALC",
      "STUDYID",
      "LBSEQ",
      "LBSTRESC",
      "DOMAIN"
    )
  )

  # Check ADSL table generated by program 3
  expect_no_error(x[[3]] |> source())
  expect_setequal(names(ADSL), cols_adsl1)

  write_adam_programs(
    dir = path_trial,
    programs = actual$programs,
    style = TRUE
  )
  # Check ADSL table generated by program 1 (no dependencies missing, hence
  # should be able to execute)
  expect_no_error(x[[1]] |> source())
  # Check ADLB program (cannot execute due to lack of LBSTRESN)
  expect_error(x[[2]] |> source())
  # Check ADSL program (cannot execute due to left join with ADLB)
  expect_error(x[[3]] |> source())
})
