test_that("No source data makes all actions non-executable", {
  # SETUP -------------------------------------------------------------------

  trial_path <- withr::local_tempdir()

  yml <- "
id: ADSL
label: Subject Level Analysis Dataset
class: SUBJECT LEVEL ANALYSIS DATASET
structure: One record per subject
keys: [USUBJID]
population:
  base:
    - domain: DM
      depends:
        - NA
      filter: NA
  global:
    - filter: NA
      depends:
        - NA

columns:
  - id: USUBJID
  - id: SEX
  - id: AGE
  - id: AGEU

"
  mighty_yml_content <- readLines(test_path("fixtures", "_mighty_sdtm.yml")) |>
    paste(collapse = "\n")
  ui_data <- setup_study_dir(list(
    "adsl" = yml,
    "_mighty" = mighty_yml_content
  ))
  setup_testdata(
    testdata = "pharmaverse",
    test_data_path = trial_path,
    sdtm_domains = "vs"
  )
  cnt <- connector::connect(file.path(trial_path, "_connector.yml"))

  # ACT ---------------------------------------------------------------------

  actual <- generate_adam_code(
    adam_specifications = ui_data,
    path_connector_config = trial_path,
    check_cross_domain_adam_dependencies = TRUE,
    data_context = data_context$new(cnt)
  )

  # EXPECT ------------------------------------------------------------------

  # No datasets used in ADaM specs exist, hence executable status should
  # be false for all actions
  expect_true(all(!actual$executable_program_sequence$can_execute))

  # Test all lines in the generated program based on missing data are either
  # empty string or starts as a comment
  code_lines <- strsplit(actual$executable_programs[[1]], "\\n")[[1]]
  expect_true(all(grepl("^#.*", code_lines) | code_lines == ""))
})

test_that("Available source data makes all actions executable", {
  # SETUP -------------------------------------------------------------------
  trial_path <- withr::local_tempdir()

  yml <- "
id: ADSL
label: Subject Level Analysis Dataset
class: SUBJECT LEVEL ANALYSIS DATASET
structure: One record per subject
keys: [USUBJID]
population:
  base:
    - domain: DM
      depends:
        - NA
      filter: NA
  global:
    - filter: NA
      depends:
        - NA

columns:
  - id: STUDYID
  - id: USUBJID
  - id: SEX
  - id: AGE
  - id: AGEU

"
  mighty_yml_content <- readLines(test_path("fixtures", "_mighty_sdtm.yml")) |>
    paste(collapse = "\n")
  ui_data <- setup_study_dir(list(
    "adsl" = yml,
    "_mighty" = mighty_yml_content
  ))
  setup_testdata(
    testdata = "pharmaverse",
    test_data_path = trial_path,
    sdtm_domains = c("dm")
  )
  cnt <- connector::connect(file.path(trial_path, "_connector.yml"))

  # ACT ---------------------------------------------------------------------

  actual <- generate_adam_code(
    adam_specifications = ui_data,
    path_connector_config = trial_path,
    check_cross_domain_adam_dependencies = TRUE,
    data_context = data_context$new(cnt)
  )

  # EXPECT ------------------------------------------------------------------

  # dm domain (small letters) exist, hence executable status should
  # be true for all actions
  expect_true(all(actual$executable_program_sequence$can_execute))
  expect_identical(actual$programs[[1]], actual$executable_programs[[1]])

  # Check executable program can be run
  write_adam_programs(
    dir = trial_path,
    programs = actual$executable_programs,
    style = TRUE
  )
  x <- list.files(trial_path, pattern = ".R", full.names = TRUE)
  expect_no_error(x[[1]] |> source())

  # Check ADSL generated by executable program
  expect_setequal(names(ADSL), c("STUDYID", "USUBJID", "SEX", "AGE", "AGEU"))
  expect_true(nrow(ADSL) > 0)
})

test_that("Missing variable in source data makes filter action non-executable", {
  # SETUP -------------------------------------------------------------------
  trial_path <- withr::local_tempdir()

  yml <- "
id: ADSL
label: Subject Level Analysis Dataset
class: SUBJECT LEVEL ANALYSIS DATASET
structure: One record per subject
keys: [USUBJID]
population:
  base:
    - domain: DM
      depends:
        - SEX
      filter: '!is.na(SEX)'
  global:
    - filter: NA
      depends:
        - NA

columns:
  - id: STUDYID
  - id: USUBJID
  - id: SEX
  - id: AGE
  - id: AGEU

"
  # Setup test data with dm domain but remove dm.SEX and dm.AGEU
  setup_testdata(
    testdata = "pharmaverse",
    test_data_path = trial_path,
    sdtm_domains = c("dm"),
    remove_cols = data.table(domain = c("dm"), columns = c("SEX", "AGEU"))
  )
  mighty_yml_content <- readLines(test_path("fixtures", "_mighty_sdtm.yml")) |>
    paste(collapse = "\n")
  ui_data <- setup_study_dir(list(
    "adsl" = yml,
    "_mighty" = mighty_yml_content
  ))
  cnt <- connector::connect(file.path(trial_path, "_connector.yml"))

  # ACT ---------------------------------------------------------------------

  actual <- generate_adam_code(
    adam_specifications = ui_data,

    path_connector_config = trial_path,
    check_cross_domain_adam_dependencies = TRUE,
    data_context = data_context$new(cnt)
  )

  # EXPECT ------------------------------------------------------------------

  # Expect filter cannot execute due to missing column SEX
  expect_false(actual$executable_program_sequence[3]$can_execute)
  expect_setequal(
    actual$executable_program_sequence$removed_outputs[[1]],
    c("DM.SEX", "DM.AGEU")
  )
  expect_setequal(
    actual$executable_program_sequence$removed_outputs[[2]],
    c("ADSL.SEX", "ADSL.AGEU")
  )

  expect_true(grepl("Filter cannot be applied", actual$executable_programs))
  expect_true(grepl(
    "#(.)+dplyr::filter(.)+na\\(SEX\\)",
    actual$executable_programs
  ))
  expect_false(grepl(
    "\\n^#(.)+dplyr::filter(.)+na\\(SEX\\)",
    actual$executable_programs
  ))

  # Check executable program can be run
  write_adam_programs(
    dir = trial_path,
    programs = actual$executable_programs,
    style = TRUE
  )
  x <- list.files(trial_path, pattern = ".R", full.names = TRUE)
  expect_no_error(x[[1]] |> source())

  # Check ADSL generated by executable program
  expect_setequal(names(ADSL), c("STUDYID", "USUBJID", "AGE"))
  expect_true(nrow(ADSL) > 0)
})

test_that("Missing variable in source data with no filter impact keeps filter executable", {
  # SETUP -------------------------------------------------------------------

  trial_path <- withr::local_tempdir()

  yml <- "
id: ADSL
label: Subject Level Analysis Dataset
class: SUBJECT LEVEL ANALYSIS DATASET
structure: One record per subject
keys: [USUBJID]
population:
  base:
    - domain: DM
      depends:
        - SEX
      filter: '!is.na(SEX)'
  global:
    - filter: NA
      depends:
        - NA

columns:
  - id: STUDYID
  - id: USUBJID
  - id: SEX
  - id: AGE
  - id: AGEU

"

  # Setup test data with dm domain but remove dm.AGEU
  setup_testdata(
    testdata = "pharmaverse",
    test_data_path = trial_path,
    sdtm_domains = c("dm"),
    remove_cols = data.table(domain = c("dm"), columns = c("AGEU"))
  )
  mighty_yml_content <- readLines(test_path("fixtures", "_mighty_sdtm.yml")) |>
    paste(collapse = "\n")
  ui_data <- setup_study_dir(list(
    "adsl" = yml,
    "_mighty" = mighty_yml_content
  ))
  cnt <- connector::connect(file.path(trial_path, "_connector.yml"))

  # ACT ---------------------------------------------------------------------

  actual <- generate_adam_code(
    adam_specifications = ui_data,

    path_connector_config = trial_path,
    check_cross_domain_adam_dependencies = TRUE,
    data_context = data_context$new(cnt)
  )

  # EXPECT ------------------------------------------------------------------

  # Expect filter is not impacted by missing column AGEU
  expect_true(actual$executable_program_sequence[3]$can_execute)
  expect_identical(
    actual$executable_program_sequence[1]$removed_outputs,
    c("DM.AGEU")
  )
  expect_identical(
    actual$executable_program_sequence[2]$removed_outputs,
    c("ADSL.AGEU")
  )

  # Check executable program can be run
  write_adam_programs(
    dir = trial_path,
    programs = actual$executable_programs,
    style = TRUE
  )
  x <- list.files(trial_path, pattern = ".R", full.names = TRUE)
  expect_no_error(x[[1]] |> source())
  # Check ADSL generated by executable program
  expect_setequal(names(ADSL), c("STUDYID", "USUBJID", "AGE", "SEX"))
  expect_true(nrow(ADSL) > 0)
})

test_that("Missing variables in source data makes filter action non-executable - case with global and domain filter", {
  # SETUP -------------------------------------------------------------------
  trial_path <- withr::local_tempdir()
  yml <- "
id: ADLB
label: Laboratory Analysis Dataset
class: BASIC DATA STRUCTURE
structure: One record per subject per parameter per analysis visit
keys:
  - USUBJID
  - STUDYID
  - LBSEQ

population:
  base:
    - domain: LB
      depends:
        - LBTESTCD
      filter: 'LBTESTCD ==\"ALB\"'
  global:
    - filter: '!is.na(SEX)'
      depends:
        - ADSL.SEX
columns:
  - id: STUDYID
  - id: USUBJID
  - id: LBSEQ
  - id: SEX
    method: ADSL.SEX
  - id: VISITNUM
  - id: LBTEST
  - id: LBTESTCD

"
  # Setup test data with LB and ADSL domains but remove LB.LBTESTCD and ADSL.SEX
  setup_testdata(
    testdata = "pharmaverse",
    test_data_path = trial_path,
    sdtm_domains = c("lb"),
    adam_domains = c("adsl"),
    remove_cols = data.table(
      domain = c("lb", "adsl"),
      columns = c("LBTESTCD", "SEX")
    )
  )
  mighty_yml_content <- readLines(test_path(
    "fixtures",
    "_mighty_with_adsl_keys.yml"
  )) |>
    paste(collapse = "\n")
  ui_data <- setup_study_dir(list(
    "adlb" = yml,
    "_mighty" = mighty_yml_content
  ))
  cnt <- connector::connect(file.path(trial_path, "_connector.yml"))

  # ACT ---------------------------------------------------------------------

  actual <- generate_adam_code(
    adam_specifications = ui_data,

    path_connector_config = trial_path,
    check_cross_domain_adam_dependencies = FALSE,
    data_context = data_context$new(cnt)
  )

  # EXPECT ------------------------------------------------------------------

  # Expect filter cannot execute due to missing column SEX and AGEU
  expect_false(actual$executable_program_sequence[3]$can_execute)
  expect_identical(
    actual$executable_program_sequence[1]$removed_outputs[[1]],
    c("LB.LBTESTCD", "ADSL.SEX")
  )
  expect_identical(
    actual$executable_program_sequence[2]$removed_outputs[[1]],
    c("ADLB.LBTESTCD", "ADLB.SEX")
  )

  # Check executable program can be run
  write_adam_programs(
    dir = trial_path,
    programs = actual$executable_programs,
    style = TRUE
  )
  x <- list.files(trial_path, pattern = ".R", full.names = TRUE)
  expect_no_error(x[[1]] |> source())

  # Check ADLB generated by executable program
  expect_setequal(
    names(ADLB),
    c("STUDYID", "USUBJID", "LBSEQ", "VISITNUM", "LBTEST")
  )
  expect_true(nrow(ADLB) > 0)

  # Check complete program cannot be run
  write_adam_programs(
    dir = trial_path,
    programs = actual$programs,
    style = TRUE
  )
  expect_error(x[[1]] |> source())
})

test_that("Missing variable in source data makes actions executable but deactivates a predecessor", {
  # SETUP -------------------------------------------------------------------

  trial_path <- withr::local_tempdir()

  yml <- "
id: ADSL
label: Subject Level Analysis Dataset
class: SUBJECT LEVEL ANALYSIS DATASET
structure: One record per subject
keys: [USUBJID]
population:
  base:
    - domain: DM
      depends:
        - NA
      filter: NA
  global:
    - filter: NA
      depends:
        - NA

columns:
  - id: STUDYID
  - id: USUBJID
  - id: SEX
  - id: AGE
  - id: AGEU

"

  # Setup test data with dm domain but remove dm.SEX
  setup_testdata(
    testdata = "pharmaverse",
    test_data_path = trial_path,
    sdtm_domains = c("dm"),
    remove_cols = data.table(domain = c("dm"), columns = c("SEX"))
  )
  mighty_yml_content <- readLines(test_path("fixtures", "_mighty_sdtm.yml")) |>
    paste(collapse = "\n")
  ui_data <- setup_study_dir(list(
    "adsl" = yml,
    "_mighty" = mighty_yml_content
  ))
  cnt <- connector::connect(file.path(trial_path, "_connector.yml"))

  # ACT ---------------------------------------------------------------------

  actual <- generate_adam_code(
    adam_specifications = ui_data,

    path_connector_config = trial_path,
    check_cross_domain_adam_dependencies = TRUE,
    data_context = data_context$new(cnt)
  )

  # EXPECT ------------------------------------------------------------------

  # Expect executable status should be true for all actions
  expect_true(all(actual$executable_program_sequence$can_execute))

  # Check removed outputs from read_data action is non-empty
  expect_length(actual$executable_program_sequence[1]$removed_outputs, 1)

  # Expect a message regarding missing column SEX
  expect_true(length(actual$executable_program_sequence[1]$lineage) > 0)
  expect_true(all(grepl(
    "sdtm\\.DM\\.SEX",
    actual$executable_program_sequence[1]$lineage
  )))

  # Test programs are out commented
  expect_true(
    grepl(
      "# Code can be executed but the following columns are not found in source data:\\n# sdtm.DM.SEX",
      actual$executable_programs
    )
  )

  # Check executable program can be run
  write_adam_programs(
    dir = trial_path,
    programs = actual$executable_programs,
    style = TRUE
  )
  x <- list.files(trial_path, pattern = ".R", full.names = TRUE)
  expect_no_error(x[[1]] |> source())

  # Check ADSL generated by executable program
  expect_setequal(names(ADSL), c("STUDYID", "USUBJID", "AGE", "AGEU"))
  expect_true(nrow(ADSL) > 0)
})

test_that("Missing domain in source data makes actions non-executable", {
  # SETUP -------------------------------------------------------------------

  trial_path <- withr::local_tempdir()

  yml <- "
id: ADSL
label: Subject Level Analysis Dataset
class: SUBJECT LEVEL ANALYSIS DATASET
structure: One record per subject
keys: [USUBJID]
population:
  base:
    - domain: DM
      depends:
        - NA
      filter: NA
    - domain: DM_VACCINE
      depends:
        - NA
      filter: NA
  global:
    - filter: NA
      depends:
        - NA

columns:
  - id: STUDYID
  - id: USUBJID
  - id: SEX
  - id: AGE
  - id: AGEU

"

  # Setup test data with dm domain but without dm_vaccine
  setup_testdata(
    testdata = "pharmaverse",
    test_data_path = trial_path,
    sdtm_domains = c("dm")
  )
  mighty_yml_content <- readLines(test_path("fixtures", "_mighty_sdtm.yml")) |>
    paste(collapse = "\n")
  ui_data <- setup_study_dir(list(
    "adsl" = yml,
    "_mighty" = mighty_yml_content
  ))
  cnt <- connector::connect(file.path(trial_path, "_connector.yml"))

  # ACT ---------------------------------------------------------------------

  actual <- generate_adam_code(
    adam_specifications = ui_data,

    path_connector_config = trial_path,
    check_cross_domain_adam_dependencies = TRUE,
    data_context = data_context$new(cnt)
  )

  # EXPECT ------------------------------------------------------------------

  # Expect executable status should be false for all actions
  expect_true(all(!actual$executable_program_sequence$can_execute))

  # Expect a message regarding missing dataset dm_vaccine
  expect_true(grepl(
    "sdtm\\.DM_VACCINE",
    actual$executable_program_sequence[1]$lineage
  ))

  # Expect all program lines are blank or starts with #
  code_lines <- strsplit(actual$executable_programs[[1]], "\\n")
  expect_true(all(sapply(code_lines[[1]], \(x) {
    (x == "" || substr(x, 1, 1) == "#")
  })))
})

test_that("Missing columns in one base domain are disregarded in other base domains", {
  #yaml file with three base domains
  # check that missing column affects other domains
  trial_path <- withr::local_tempdir()

  yml <- "
id: ADSL
label: Subject Level Analysis Dataset
class: SUBJECT LEVEL ANALYSIS DATASET
structure: One record per subject
keys: [USUBJID]
population:
  base:
    - domain: DM
      depends:
        - NA
      filter: NA
    - domain: SV
      depends:
        - NA
      filter: NA
    - domain: DM_VACCINE
      depends:
        - NA
      filter: NA
  global:
    - filter: NA
      depends:
        - NA

columns:
  - id: STUDYID
  - id: USUBJID
  - id: SEX
  - id: AGE
  - id: AGEU

"

  # Setup test data with sv, dm and dm_vaccine domains
  setup_testdata(
    testdata = "pharmaverse",
    test_data_path = trial_path,
    sdtm_domains = c("dm", "dm_vaccine", "sv")
  )
  mighty_yml_content <- readLines(test_path("fixtures", "_mighty_sdtm.yml")) |>
    paste(collapse = "\n")
  ui_data <- setup_study_dir(list(
    "adsl" = yml,
    "_mighty" = mighty_yml_content
  ))
  cnt <- connector::connect(file.path(trial_path, "_connector.yml"))

  # ACT ---------------------------------------------------------------------

  actual <- generate_adam_code(
    adam_specifications = ui_data,

    path_connector_config = trial_path,
    check_cross_domain_adam_dependencies = TRUE,
    data_context = data_context$new(cnt)
  )

  # EXPECT ------------------------------------------------------------------

  # Check removed outputs from read_data action
  expect_setequal(
    actual$executable_program_sequence[1]$removed_outputs[[1]],
    c(
      "DM.SEX",
      "DM.AGE",
      "DM.AGEU",
      "SV.SEX",
      "SV.AGE",
      "SV.AGEU",
      "DM_VACCINE.SEX",
      "DM_VACCINE.AGE",
      "DM_VACCINE.AGEU"
    )
  )

  # Check comments in executable program
  expect_true(
    grepl(
      "# Code can be executed but the following columns are not found in source data:\\n# sdtm.SV.SEX, sdtm.SV.AGE, sdtm.SV.AGEU", # nolint: line_length_linter
      actual$executable_programs
    )
  )
  expect_true(
    grepl(
      "\\n# This impacts the following data that will be ignored:\\n# sdtm.DM.SEX, sdtm.DM.AGE, sdtm.DM.AGEU, sdtm.SV.SEX, sdtm.SV.AGE, sdtm.SV.AGEU, sdtm.DM_VACCINE.SEX, sdtm.DM_VACCINE.AGE, sdtm.DM_VACCINE.AGEU", # nolint: line_length_linter
      actual$executable_programs
    )
  )

  # Check executable program can be run
  write_adam_programs(
    dir = trial_path,
    programs = actual$executable_programs,
    style = TRUE
  )
  x <- list.files(trial_path, pattern = ".R", full.names = TRUE)
  expect_no_error(x |> source())

  # Check ADSL table generated by executable program
  expect_setequal(names(ADSL), c("STUDYID", "USUBJID"))
  expect_true(nrow(ADSL) > 0)

  # Check complete program cannot be run
  write_adam_programs(
    dir = trial_path,
    programs = actual$programs,
    style = TRUE
  )
  expect_error(x |> source(), "Can't select columns that don't exist.")
})

test_that("Filter removes missing base domain variables and creates lineage message", {
  # SETUP -------------------------------------------------------------------
  trial_path <- withr::local_tempdir()

  yml <- "
id: ADLB
label: Laboratory Analysis Dataset
class: BASIC DATA STRUCTURE
structure: One record per subject per parameter per analysis visit
keys:
  - USUBJID
  - STUDYID
  - LBSEQ
population:
  base:
    - domain: LB
      depends:
        - NA
      filter: NA
  global:
    - filter: '!is.na(SEX)'
      depends:
        - ADSL.SEX
columns:
  - id: STUDYID
  - id: USUBJID
  - id: SEX
    method: ADSL.SEX
  - id: LBSTRESN
  - id: LBSEQ

"

  # Setup test data with LB and ADSL domains but remove LB.LBSTRESN
  setup_testdata(
    testdata = "pharmaverse",
    test_data_path = trial_path,
    sdtm_domains = c("lb"),
    adam_domains = c("adsl"),
    remove_cols = data.table(domain = c("lb"), columns = c("LBSTRESN"))
  )
  mighty_yml_content <- readLines(test_path(
    "fixtures",
    "_mighty_with_adsl_keys.yml"
  )) |>
    paste(collapse = "\n")
  ui_data <- setup_study_dir(list(
    "adlb" = yml,
    "_mighty" = mighty_yml_content
  ))
  cnt <- connector::connect(file.path(trial_path, "_connector.yml"))

  # ACT ---------------------------------------------------------------------

  actual <- generate_adam_code(
    adam_specifications = ui_data,

    path_connector_config = trial_path,
    check_cross_domain_adam_dependencies = FALSE,
    data_context = data_context$new(cnt)
  )

  # EXPECT ------------------------------------------------------------------

  # Expect filter is impacted by missing LBSTRESN but can execute with
  # lineage message

  eps <- actual$executable_program_sequence
  # Expect executable status should be true for all actions
  expect_true(eps[3]$can_execute)

  # Check lineage message
  expect_identical(
    eps[3]$lineage,
    "Code can be executed but the following columns are not found in source data and are ignored in the filter step:\nadam.ADLB.LBSTRESN" # nolint: line_length_linter
  )
  # Check removed outputs from read_data and init_domain actions
  expect_identical(
    eps[node_id == "ADLB-1-read_data"]$removed_outputs[[1]],
    "LB.LBSTRESN"
  )
  expect_identical(
    eps[node_id == "ADLB-init_domain"]$removed_outputs[[1]],
    "ADLB.LBSTRESN"
  )

  # Check executable program can be run
  write_adam_programs(
    dir = trial_path,
    programs = actual$executable_programs,
    style = TRUE
  )
  x <- list.files(trial_path, pattern = ".R", full.names = TRUE)
  expect_no_error(x[[1]] |> source())

  # Check ADSL table generated by executable program and verify LBSTRESN is missing
  expect_setequal(names(ADLB), c("STUDYID", "USUBJID", "SEX", "LBSEQ"))
})
