test_that("No source data makes all actions non-executable", {
  # SETUP -------------------------------------------------------------------

  trial_path <- withr::local_tempdir()

  yml <- "
table:
  name: ADSL
init:
  base_domains:
    - DM
  filter_domain:
    - DM: NA
  filter_global:
    - NA
  filter_depend_cols:
    - NA
column_action:
  USUBJID:
  SEX:
  AGE:
  AGEU:

"
  ui_data <- create_temp_yaml(yml)
  pt <- prepare_test(trial_path, yml, c("dm"))
  cnt <- connector::connect(file.path(trial_path, "_connector.yml"))

  # ACT ---------------------------------------------------------------------

  actual <- generate_adam_code(
    path_ui_data = ui_data,
    path_trial_metadata = pt$path_trial_metadata,
    path_trial = trial_path,
    check_cross_domain_adam_dependencies = TRUE,
    data_context = data_context$new(cnt)
  )

  # EXPECT ------------------------------------------------------------------

  # DM domain (capital letters) does not exist, hence executable status should
  # be false for all actions
  expect_true(all(!actual$executable_program_sequence$can_execute))

  # Test all lines in the generated program based on missing data are either
  # empty string or starts as a comment
  code_lines <- strsplit(actual$executable_programs[[1]], "\\n")[[1]]
  expect_true(all(grepl("^#.*", code_lines) | code_lines == ""))
})

test_that("Available source data makes all actions executable", {
  # SETUP -------------------------------------------------------------------
  trial_path <- withr::local_tempdir()

  yml <- "
table:
  name: ADSL
init:
  base_domains:
    - dm
  filter_domain:
    - dm: NA
  filter_global:
    - NA
  filter_depend_cols:
    - NA
column_action:
  STUDYID:
  USUBJID:
  SEX:
  AGE:
  AGEU:


"
  ui_data <- create_temp_yaml(yml)
  pt <- prepare_test(trial_path, yml, c("dm"))
  cnt <- connector::connect(file.path(trial_path, "_connector.yml"))

  # ACT ---------------------------------------------------------------------

  actual <- generate_adam_code(
    path_ui_data = ui_data,
    path_trial_metadata = pt$path_trial_metadata,
    path_trial = trial_path,
    check_cross_domain_adam_dependencies = TRUE,
    data_context = data_context$new(cnt)
  )

  # EXPECT ------------------------------------------------------------------

  # dm domain (small letters) exist, hence executable status should
  # be true for all actions
  expect_true(all(actual$executable_program_sequence$can_execute))
  expect_identical(actual$programs[[1]], actual$executable_programs[[1]])

  # Check executable program can be run
  write_adam_programs(
    dir = trial_path,
    programs = actual$executable_programs,
    style = TRUE
  )
  x <- list.files(trial_path, pattern = ".R", full.names = TRUE)
  expect_no_error(x[[1]] |> source())

  # Check ADSL generated by executable program
  expect_setequal(names(ADSL), c("STUDYID", "USUBJID", "SEX", "AGE", "AGEU"))
  expect_true(nrow(ADSL) > 0)
})

test_that("Missing variable in source data makes filter action non-executable", {
  # SETUP -------------------------------------------------------------------
  trial_path <- withr::local_tempdir()

  yml <- "
table:
  name: ADSL
init:
  base_domains:
    - dm
  filter_domain:
    - dm: '!is.na(SEX)'
  filter_global:
    - NA
  filter_depend_cols:
    - SEX
column_action:
  STUDYID:
  USUBJID:
  SEX:
  AGE:
  AGEU:


"
  # Setup test data with dm domain but remove dm.SEX and dm.AGEU
  pt <- prepare_test(
    trial_path,
    yml,
    c("dm"),
    remove_data = data.table(domain = c("dm"), columns = c("SEX", "AGEU"))
  )
  ui_data <- create_temp_yaml(yml)
  cnt <- connector::connect(file.path(trial_path, "_connector.yml"))

  # ACT ---------------------------------------------------------------------

  actual <- generate_adam_code(
    path_ui_data = ui_data,
    path_trial_metadata = pt$path_trial_metadata,
    path_trial = trial_path,
    check_cross_domain_adam_dependencies = TRUE,
    data_context = data_context$new(cnt)
  )

  # EXPECT ------------------------------------------------------------------

  # Expect filter cannot execute due to missing column SEX
  expect_false(actual$executable_program_sequence[3]$can_execute)
  expect_setequal(
    actual$executable_program_sequence$removed_outputs[[1]],
    c("dm.SEX", "dm.AGEU")
  )
  expect_setequal(
    actual$executable_program_sequence$removed_outputs[[2]],
    c("ADSL.SEX", "ADSL.AGEU")
  )

  expect_true(grepl("Filter cannot be applied", actual$executable_programs))
  expect_true(grepl(
    "#(.)+dplyr::filter(.)+na\\(SEX\\)",
    actual$executable_programs
  ))
  expect_false(grepl(
    "\\n^#(.)+dplyr::filter(.)+na\\(SEX\\)",
    actual$executable_programs
  ))

  # Check executable program can be run
  write_adam_programs(
    dir = trial_path,
    programs = actual$executable_programs,
    style = TRUE
  )
  x <- list.files(trial_path, pattern = ".R", full.names = TRUE)
  expect_no_error(x[[1]] |> source())

  # Check ADSL generated by executable program
  expect_setequal(names(ADSL), c("STUDYID", "USUBJID", "AGE"))
  expect_true(nrow(ADSL) > 0)
})

test_that("Missing variable in source data with no filter impact keeps filter executable", {
  # SETUP -------------------------------------------------------------------

  trial_path <- withr::local_tempdir()

  yml <- "
table:
  name: ADSL
init:
  base_domains:
    - dm
  filter_domain:
    - dm: '!is.na(SEX)'
  filter_global:
    - NA
  filter_depend_cols:
    - SEX
column_action:
  STUDYID:
  USUBJID:
  SEX:
  AGE:
  AGEU:

"

  # Setup test data with dm domain but remove dm.AGEU
  pt <- prepare_test(
    trial_path,
    yml,
    c("dm"),
    remove_data = data.table(domain = c("dm"), columns = c("AGEU"))
  )
  ui_data <- create_temp_yaml(yml)
  cnt <- connector::connect(file.path(trial_path, "_connector.yml"))

  # ACT ---------------------------------------------------------------------

  actual <- generate_adam_code(
    path_ui_data = ui_data,
    path_trial_metadata = pt$path_trial_metadata,
    path_trial = trial_path,
    check_cross_domain_adam_dependencies = TRUE,
    data_context = data_context$new(cnt)
  )

  # EXPECT ------------------------------------------------------------------

  # Expect filter is not impacted by missing column AGEU
  expect_true(actual$executable_program_sequence[3]$can_execute)
  expect_identical(
    actual$executable_program_sequence[1]$removed_outputs,
    c("dm.AGEU")
  )
  expect_identical(
    actual$executable_program_sequence[2]$removed_outputs,
    c("ADSL.AGEU")
  )

  # Check executable program can be run
  write_adam_programs(
    dir = trial_path,
    programs = actual$executable_programs,
    style = TRUE
  )
  x <- list.files(trial_path, pattern = ".R", full.names = TRUE)
  expect_no_error(x[[1]] |> source())

  # Check ADSL generated by executable program
  expect_setequal(names(ADSL), c("STUDYID", "USUBJID", "AGE", "SEX"))
  expect_true(nrow(ADSL) > 0)
})

test_that("Missing variables in source data makes filter action non-executable - case with global and domain filter", {
  # SETUP -------------------------------------------------------------------

  trial_path <- withr::local_tempdir()
  yml <- "
table:
  name: ADLB
init:
  base_domains:
    - lb
  filter_domain:
    - lb: 'LBTESTCD ==\"ALB\"'
  filter_global:
    - '!is.na(SEX)'
  filter_depend_cols:
    - adsl.SEX
    - LBTESTCD
column_action:
  STUDYID:
  USUBJID:
  LBSEQ:
  SEX:
    source: adsl.SEX
  VISITNUM:
  LBTEST:
  LBTESTCD:

"
  # Setup test data with lb and adsl domains but remove lb.LBTESTCD and adsl.SEX
  pt <- prepare_test(
    trial_path,
    yml,
    c("lb"),
    c("adsl"),
    remove_data = data.table(
      domain = c("lb", "adsl"),
      columns = c("LBTESTCD", "SEX")
    )
  )
  ui_data <- create_temp_yaml(yml)
  cnt <- connector::connect(file.path(trial_path, "_connector.yml"))

  # ACT ---------------------------------------------------------------------

  actual <- generate_adam_code(
    path_ui_data = ui_data,
    path_trial_metadata = pt$path_trial_metadata,
    path_trial = trial_path,
    check_cross_domain_adam_dependencies = FALSE,
    data_context = data_context$new(cnt)
  )

  # EXPECT ------------------------------------------------------------------

  # Expect filter cannot execute due to missing column SEX and AGEU
  expect_false(actual$executable_program_sequence[3]$can_execute)
  expect_identical(
    actual$executable_program_sequence[1]$removed_outputs[[1]],
    c("lb.LBTESTCD", "adsl.SEX")
  )
  expect_identical(
    actual$executable_program_sequence[2]$removed_outputs[[1]],
    c("ADLB.LBTESTCD", "ADLB.SEX")
  )

  # Check executable program can be run
  write_adam_programs(
    dir = trial_path,
    programs = actual$executable_programs,
    style = TRUE
  )
  x <- list.files(trial_path, pattern = ".R", full.names = TRUE)
  expect_no_error(x[[1]] |> source())

  # Check ADLB generated by executable program
  expect_setequal(
    names(ADLB),
    c("STUDYID", "USUBJID", "LBSEQ", "VISITNUM", "LBTEST")
  )
  expect_true(nrow(ADLB) > 0)

  # Check complete program cannot be run
  write_adam_programs(
    dir = trial_path,
    programs = actual$programs,
    style = TRUE
  )
  expect_error(x[[1]] |> source())
})

test_that("Missing variable in source data makes actions executable but deactivates a predecessor", {
  # SETUP -------------------------------------------------------------------

  trial_path <- withr::local_tempdir()

  yml <- "
table:
  name: ADSL
init:
  base_domains:
    - dm
  filter_domain:
    - dm: NA
  filter_global:
    - NA
  filter_depend_cols:
    - NA
column_action:
  STUDYID:
  USUBJID:
  SEX:
  AGE:
  AGEU:

"

  # Setup test data with dm domain but remove dm.SEX
  pt <- prepare_test(
    trial_path,
    yml,
    c("dm"),
    remove_data = data.table(domain = c("dm"), columns = c("SEX"))
  )
  ui_data <- create_temp_yaml(yml)
  cnt <- connector::connect(file.path(trial_path, "_connector.yml"))

  # ACT ---------------------------------------------------------------------

  actual <- generate_adam_code(
    path_ui_data = ui_data,
    path_trial_metadata = pt$path_trial_metadata,
    path_trial = trial_path,
    check_cross_domain_adam_dependencies = TRUE,
    data_context = data_context$new(cnt)
  )

  # EXPECT ------------------------------------------------------------------

  # Expect executable status should be true for all actions
  expect_true(all(actual$executable_program_sequence$can_execute))

  # Check removed outputs from read_data action is non-empty
  expect_length(actual$executable_program_sequence[1]$removed_outputs, 1)

  # Expect a message regarding missing column SEX
  expect_true(length(actual$executable_program_sequence[1]$lineage) > 0)
  expect_true(all(grepl(
    "sdtm\\.dm\\.SEX",
    actual$executable_program_sequence[1]$lineage
  )))

  # Test programs are out commented
  expect_true(
    grepl(
      "# Code can be executed but the following columns are not found in source data:\\n# sdtm.dm.SEX",
      actual$executable_programs
    )
  )

  # Check executable program can be run
  write_adam_programs(
    dir = trial_path,
    programs = actual$executable_programs,
    style = TRUE
  )
  x <- list.files(trial_path, pattern = ".R", full.names = TRUE)
  expect_no_error(x[[1]] |> source())

  # Check ADSL generated by executable program
  expect_setequal(names(ADSL), c("STUDYID", "USUBJID", "AGE", "AGEU"))
  expect_true(nrow(ADSL) > 0)
})

test_that("Missing domain in source data makes actions non-executable", {
  # SETUP -------------------------------------------------------------------

  trial_path <- withr::local_tempdir()

  yml <- "
table:
  name: ADSL
init:
  base_domains:
    - dm
    - dm_vaccine
  filter_domain:
    - dm: NA
    - dm_vaccine: NA
  filter_global:
    - NA
  filter_depend_cols:
    - NA
column_action:
  STUDYID:
  USUBJID:
  SEX:
  AGE:
  AGEU:


"

  # Setup test data with dm domain but without dm_vaccine
  pt <- prepare_test(trial_path, yml, c("dm"))
  ui_data <- create_temp_yaml(yml)
  cnt <- connector::connect(file.path(trial_path, "_connector.yml"))

  # ACT ---------------------------------------------------------------------

  actual <- generate_adam_code(
    path_ui_data = ui_data,
    path_trial_metadata = pt$path_trial_metadata,
    path_trial = trial_path,
    check_cross_domain_adam_dependencies = TRUE,
    data_context = data_context$new(cnt)
  )

  # EXPECT ------------------------------------------------------------------

  # Expect executable status should be false for all actions
  expect_true(all(!actual$executable_program_sequence$can_execute))

  # Expect a message regarding missing dataset dm_vaccine
  expect_true(grepl(
    "sdtm\\.dm_vaccine",
    actual$executable_program_sequence[1]$lineage
  ))

  # Expect all program lines are blank or starts with #
  code_lines <- strsplit(actual$executable_programs[[1]], "\\n")
  expect_true(all(sapply(code_lines[[1]], \(x) {
    (x == "" || substr(x, 1, 1) == "#")
  })))
})

test_that("Missing base domain does not allow execution based on available data in other base domains", {
  #yaml file with three base domains
  # NOTE: More or less identical with the test
  # "Missing domain in source data makes actions non-executable"
  # Differs since DM domain is not available. May be a use case, if the specs
  # are not taking casing into account

  trial_path <- withr::local_tempdir()

  yml <- "
table:
  name: ADSL
init:
  base_domains:
    - dm
    - DM
    - dm_vaccine
  filter_domain:
    - dm: NA
    - DM: NA
    - dm_vaccine: NA
  filter_global:
    - NA
  filter_depend_cols:
    - NA
column_action:
  STUDYID:
  USUBJID:
  SEX:
  AGE:
  AGEU:


"

  # Setup test data with dm and dm_vaccine domains
  pt <- prepare_test(trial_path, yml, c("dm", "dm_vaccine"))
  ui_data <- create_temp_yaml(yml)
  cnt <- connector::connect(file.path(trial_path, "_connector.yml"))

  # ACT ---------------------------------------------------------------------

  actual <- generate_adam_code(
    path_ui_data = ui_data,
    path_trial_metadata = pt$path_trial_metadata,
    path_trial = trial_path,
    check_cross_domain_adam_dependencies = TRUE,
    data_context = data_context$new(cnt)
  )

  # EXPECT ------------------------------------------------------------------

  # TODO: Here code will not be able to execute at all, even though dm and
  # dm_vaccine domains are complete. A modification to the handle_read_data_action
  # processing will be needed, if such a requirement occurs

  # Expect executable status should be false for all actions
  expect_true(all(!actual$executable_program_sequence$can_execute))

  # Expect a message regarding missing dataset DM
  expect_true(grepl("sdtm\\.DM", actual$executable_program_sequence[1]$lineage))

  # Expect all program lines are blank or starts with #
  code_lines <- strsplit(actual$executable_programs[[1]], "\\n")
  expect_true(all(sapply(code_lines[[1]], \(x) {
    (x == "" || substr(x, 1, 1) == "#")
  })))
})

test_that("Missing columns in one base domain are disregarded in other base domains", {
  #yaml file with three base domains
  # check that missing column affects other domains
  trial_path <- withr::local_tempdir()

  yml <- "
table:
  name: ADSL
init:
  base_domains:
    - dm
    - sv
    - dm_vaccine
  filter_domain:
    - dm: NA
    - sv: NA
    - dm_vaccine: NA
  filter_global:
    - NA
  filter_depend_cols:
    - NA
column_action:
  STUDYID:
  USUBJID:
  SEX:
  AGE:
  AGEU:


"

  # Setup test data with sv, dm and dm_vaccine domains
  pt <- prepare_test(trial_path, yml, c("dm", "dm_vaccine", "sv"))
  ui_data <- create_temp_yaml(yml)
  cnt <- connector::connect(file.path(trial_path, "_connector.yml"))

  # ACT ---------------------------------------------------------------------

  actual <- generate_adam_code(
    path_ui_data = ui_data,
    path_trial_metadata = pt$path_trial_metadata,
    path_trial = trial_path,
    check_cross_domain_adam_dependencies = TRUE,
    data_context = data_context$new(cnt)
  )

  # EXPECT ------------------------------------------------------------------

  # Check removed outputs from read_data action
  expect_setequal(
    actual$executable_program_sequence[1]$removed_outputs[[1]],
    c(
      "dm.SEX",
      "dm.AGE",
      "dm.AGEU",
      "sv.SEX",
      "sv.AGE",
      "sv.AGEU",
      "dm_vaccine.SEX",
      "dm_vaccine.AGE",
      "dm_vaccine.AGEU"
    )
  )

  # Check comments in executable program
  expect_true(
    grepl(
      "# Code can be executed but the following columns are not found in source data:\\n# sdtm.sv.SEX, sdtm.sv.AGE, sdtm.sv.AGEU", # nolint: line_length_linter
      actual$executable_programs
    )
  )
  expect_true(
    grepl(
      "\\n# This impacts the following data that will be ignored:\\n# sdtm.dm.SEX, sdtm.dm.AGE, sdtm.dm.AGEU, sdtm.sv.SEX, sdtm.sv.AGE, sdtm.sv.AGEU, sdtm.dm_vaccine.SEX, sdtm.dm_vaccine.AGE, sdtm.dm_vaccine.AGEU", # nolint: line_length_linter
      actual$executable_programs
    )
  )

  # Check executable program can be run
  write_adam_programs(
    dir = trial_path,
    programs = actual$executable_programs,
    style = TRUE
  )
  x <- list.files(trial_path, pattern = ".R", full.names = TRUE)
  expect_no_error(x |> source())

  # Check ADSL table generated by executable program
  expect_setequal(names(ADSL), c("STUDYID", "USUBJID"))
  expect_true(nrow(ADSL) > 0)

  # Check complete program cannot be run
  write_adam_programs(
    dir = trial_path,
    programs = actual$programs,
    style = TRUE
  )
  expect_error(x |> source(), "Can't select columns that don't exist.")
})

test_that("Filter removes missing base domain variables and creates lineage message", {
  # SETUP -------------------------------------------------------------------
  trial_path <- withr::local_tempdir()

  yml <- "
table:
  name: ADLB
init:
  base_domains:
    - lb
  filter_domain:
    - lb: NA
  filter_global:
    - '!is.na(SEX)'
  filter_depend_cols:
    - adsl.SEX
column_action:
  STUDYID:
  USUBJID:
  SEX:
    source: adsl.SEX
  LBSTRESN:
  LBSEQ:

"

  # Setup test data with dm domain but remove dm.AGEU
  pt <- prepare_test(
    trial_path,
    yml,
    c("lb"),
    c("adsl"),
    remove_data = data.table(domain = c("lb"), columns = c("LBSTRESN"))
  )
  ui_data <- create_temp_yaml(yml)
  cnt <- connector::connect(file.path(trial_path, "_connector.yml"))

  # ACT ---------------------------------------------------------------------

  actual <- generate_adam_code(
    path_ui_data = ui_data,
    path_trial_metadata = pt$path_trial_metadata,
    path_trial = trial_path,
    check_cross_domain_adam_dependencies = FALSE,
    data_context = data_context$new(cnt)
  )

  # EXPECT ------------------------------------------------------------------

  # Expect filter is impacted by missing LBSTRESN but can execute with
  # lineage message

  eps <- actual$executable_program_sequence
  # Expect executable status should be true for all actions
  expect_true(eps[3]$can_execute)

  # Check lineage message
  expect_identical(
    eps[3]$lineage,
    "Code can be executed but the following columns are not found in source data and are ignored in the filter step:\nadam.ADLB.LBSTRESN" # nolint: line_length_linter
  )
  # Check removed outputs from read_data and init_domain actions
  expect_identical(
    eps[node_id == "ADLB-1-read_data"]$removed_outputs[[1]],
    "lb.LBSTRESN"
  )
  expect_identical(
    eps[node_id == "ADLB-init_domain"]$removed_outputs[[1]],
    "ADLB.LBSTRESN"
  )

  # Check executable program can be run
  write_adam_programs(
    dir = trial_path,
    programs = actual$executable_programs,
    style = TRUE
  )
  x <- list.files(trial_path, pattern = ".R", full.names = TRUE)
  expect_no_error(x[[1]] |> source())

  # Check ADSL table generated by executable program and verify LBSTRESN is missing
  expect_setequal(names(ADLB), c("STUDYID", "USUBJID", "SEX", "LBSEQ"))
})
