test_that("Complex test with multiple domains and column/row operations", {
  # SETUP
  ui_path <- c(
    test_path("fixtures", "adsl_complex.yml"),
    test_path("fixtures", "adlb_complex.yml")
  )
  path_trial_metadata <- test_path("fixtures", "trial_metadata_0001.yml")
  std_lib_path <- c(
    testthat::test_path("fixtures", "adsl_0001.R"),
    testthat::test_path("fixtures", "adlb_0001.R")
  )

  domain_keys_path <- system.file("standards", "domain_keys.yml", package = "mighty")
  output_path <- withr::local_tempdir()

  # ACT
  actual <- generate_adam_code(
    path_ui_data = ui_path,
    code_component_source_files =  std_lib_path,
    path_trial_metadata = path_trial_metadata,
    path_domain_keys = domain_keys_path,
    path_output = output_path,
    data_connection = "pharmaverse"
  )
  write_adam_programs(dir = output_path, programs = actual$programs)

  x <- list.files(output_path, full.names = TRUE)
  programs <- x |> lapply(readLines)
  names(programs) <- basename(x)

  # Check program 1: ADSL part 1
  expect_section_order("ADSL-PLANNED_ARM", "ADSL-ARM_GRP1-arm_group_01", programs[["1_ADSL.R"]])
  expect_section_order("ADSL-PLANNED_ARM", "ADSL-NEW_ARM-arm_01", programs[["1_ADSL.R"]])
  expect_section_order("ADSL-PLANNED_ARM", "ADSL-ARM_MATCH-arm_match_01", programs[["1_ADSL.R"]])
  expect_section_order("ADSL-ARM_GRP1-arm_group_01", "ADSL-ARM_CAT1-arm_category_01", programs[["1_ADSL.R"]])
  expect_section_order("ADSL-AGE2-age_crop_01", "ADSL-AGE_DIFF1-age_diff_01", programs[["1_ADSL.R"]])
  expect_section_order(c("ADSL-PLANNED_ARM", "ADSL-AGE_DIFF1-age_diff_01"), "ADSL-AGE_DIFF2-age_diff_02", programs[["1_ADSL.R"]])
  expect_section_order(c("ADSL-PLANNED_ARM", "ADSL-AGE_DIFF1-age_diff_01"), "ADSL-NEWFL01-NEWREA01-newfl_01", programs[["1_ADSL.R"]])
  expect_section_order("ADSL-AGE2-age_crop_01", 'ADSL-AGE_GRP1-age_group_01-list(cut_points = "c(20, 45)")' , programs[["1_ADSL.R"]])

  # Check ADSL table generated by program 1
  x[[1]] |> source()
  setcolorder(ADSL, sort(names(ADSL)))
  ADSL |> expect_snapshot_value(style = "json2")

  # Check program 1: ADLB
  expect_section_order(c("ADLB-AVAL", "ADLB-LBTEST-new_lbtest_01"), "ADLB-AVAL_GRP-aval_grp_01", programs[["2_ADLB.R"]])
  expect_section_order("ADLB-AVAL-new_aval_01", "ADLB-LBTEST-lbtest_01", programs[["2_ADLB.R"]])
  expect_section_order(c("ADLB-LBTEST-new_lbtest_01", "ADLB-AVAL_GRP-aval_grp_01"), "ADLB-AVAL_GRP2-aval_grp_02", programs[["2_ADLB.R"]])
  expect_section_order("ADLB-AVAL", "ADLB-AVAL-new_aval_01", programs[["2_ADLB.R"]])
  expect_section_order("ADLB-AVAL", "ADLB-AVAL-new_aval_03", programs[["2_ADLB.R"]])
  expect_section_order(c("ADLB-AVAL", "ADLB-AVALC"), "ADLB-AVAL-new_aval_04", programs[["2_ADLB.R"]])
  expect_section_order("ADLB-LBTEST-lbtest_01", "ADLB-LBTEST-new_lbtest_01", programs[["2_ADLB.R"]])
  expect_section_order(c("ADLB-AVALC", "ADLB-LBTEST-lbtest_01"), "ADLB-LBTEST-AVALC-new_lbtest_02", programs[["2_ADLB.R"]])
  expect_section_order("ADLB-LBTEST-AVALC-new_lbtest_02", "ADLB-LBTEST-new_lbtest_04" , programs[["2_ADLB.R"]])
  expect_section_order(c("ADLB-LBTEST-new_lbtest_01", "ADLB-LBTEST-AVALC-new_lbtest_02"), "ADLB-LBTEST-new_lbtest_05", programs[["2_ADLB.R"]])
  expect_section_order(c("ADLB-LBTEST-lbtest_01", "ADLB-LBTEST-new_lbtest_01"), "ADLB-LBTEST-new_lbtest_03", programs[["2_ADLB.R"]])
  expect_section_order(c("ADLB-AVAL", "ADLB-AVAL-new_aval_01"), "ADLB-AVAL-new_aval_02", programs[["2_ADLB.R"]])
  expect_section_order("ADLB-VISITNUM-new_visitnum_01", "ADLB-VISITNUM-new_visitnum_02", programs[["2_ADLB.R"]])
  expect_section_order("ADLB-LBTEST-lbtest_01", "ADLB-LBTEST-new_lbtest_07", programs[["2_ADLB.R"]])
  expect_section_order("ADLB-LBTEST-lbtest_01", "ADLB-LBTEST-new_lbtest_07-list(test_val = \"s:Protein\")", programs[["2_ADLB.R"]])
  expect_section_order("ADLB-LBTEST-lbtest_01", "ADLB-LBTEST-new_lbtest_07-list(test_val = \"s:Specific Gravity\")", programs[["2_ADLB.R"]])

  # Check ADLB table generated by program 2
  x[[2]] |> source()
  setcolorder(ADLB, sort(names(ADLB)))
  ADLB |> expect_snapshot_value(style = "json2")

  # Check program 3: ADSL part 2
  expect_section_order("ADSL-NEWFL02-newfl_02", "ADSL-NEWFL03-NEWREA03-newfl_03", programs[["3_ADSL.R"]])

  # Check ADSL table generated by program 3
  x[[3]] |> source()
  setcolorder(ADSL, sort(names(ADSL)))
  ADSL |> expect_snapshot_value(style = "json2")

  # Check edges
  actual$edges |> as.data.frame() |> expect_snapshot_value(style = "json2")
})

