test_that("Complex test with multiple domains and column/row operations", {
  # SETUP -------------------------------------------------------------------

  adam_specifications <- setup_study_from_fixtures(
    fixtures = list(
      "adsl" = "complex_adsl.yml",
      "adlb" = "complex_adlb.yml",
      "_mighty" = "_mighty.yml"
    )
  )

  path_connector_config <- withr::local_tempdir()

  setup_testdata(
    testdata = "pharmaverse",
    test_data_path = path_connector_config,
    sdtm_domains = c("dm", "dm_vaccine", "lb", "sv")
  )
  standards_lib <- "mighty.standards"

  # ACT ---------------------------------------------------------------------

  actual <- generate_adam_code(
    adam_specifications = adam_specifications,
    standards_lib = standards_lib,
    path_connector_config = path_connector_config,
    check_cross_domain_adam_dependencies = TRUE
  )

  # EXPECT ------------------------------------------------------------------

  actual$actions |>
    names() |>
    expect_setequal(
      c(
        "code_id",
        "depend_cols",
        "depend_rows",
        "domain",
        "node_id",
        "outputs",
        "parameters",
        "type"
      )
    )
  #remove connector save step from program 3 as this will fail on Windows
  actual$programs[3][[1]] <-
    remove_connector_write_step(actual$programs[3][[1]])

  write_adam_programs(
    dir = path_connector_config,
    programs = actual$programs,
    style = TRUE
  )
  x <- list.files(path_connector_config, pattern = ".R", full.names = TRUE)

  programs <- x |> lapply(readLines)
  names(programs) <- basename(x)

  # Check program 1: ADSL part 1
  expect_section_order(
    "ADSL-PLANNED_ARM",
    "ADSL-ARM_GRP1",
    programs[["1_ADSL.R"]]
  )
  expect_section_order(
    "ADSL-PLANNED_ARM",
    "ADSL-NEW_ARM",
    programs[["1_ADSL.R"]]
  )
  expect_section_order(
    "ADSL-PLANNED_ARM",
    "ADSL-ARM_MATCH",
    programs[["1_ADSL.R"]]
  )
  expect_section_order(
    "ADSL-ARM_GRP1",
    "ADSL-ARM_CAT1",
    programs[["1_ADSL.R"]]
  )
  expect_section_order(
    "ADSL-AGE2",
    "ADSL-AGE_DIFF1",
    programs[["1_ADSL.R"]]
  )
  expect_section_order(
    c("ADSL-PLANNED_ARM", "ADSL-AGE_DIFF1"),
    "ADSL-AGE_DIFF2",
    programs[["1_ADSL.R"]]
  )
  expect_section_order(
    c("ADSL-PLANNED_ARM", "ADSL-AGE_DIFF1"),
    "ADSL-NEWFL01-NEWREA01",
    programs[["1_ADSL.R"]]
  )
  expect_section_order(
    "ADSL-AGE2",
    "ADSL-AGE_GRP1",
    programs[["1_ADSL.R"]]
  )

  # Check ADSL table generated by program 1
  x[[1]] |> source()
  setcolorder(ADSL, sort(names(ADSL)))
  ADSL |> expect_snapshot_value(style = "json2", variant = "adsl_1")

  # Check program 2: ADLB
  expect_section_order(
    c("ADLB-AVAL", "ADLB-NEW_MICROCYTES"),
    "ADLB-AVAL_GRP",
    programs[["2_ADLB.R"]]
  )
  expect_section_order(
    "ADLB-NEW_AVAL_01",
    "ADLB-LBTEST",
    programs[["2_ADLB.R"]]
  )
  expect_section_order(
    c("ADLB-NEW_MICROCYTES", "ADLB-AVAL_GRP"),
    "ADLB-AVAL_GRP2",
    programs[["2_ADLB.R"]]
  )
  expect_section_order(
    "ADLB-AVAL",
    "ADLB-NEW_AVAL_01",
    programs[["2_ADLB.R"]]
  )
  expect_section_order(
    "ADLB-AVAL",
    "ADLB-NEW_AVAL_03",
    programs[["2_ADLB.R"]]
  )
  expect_section_order(
    c("ADLB-AVAL", "ADLB-AVALC"),
    "ADLB-NEW_AVAL_04",
    programs[["2_ADLB.R"]]
  )
  expect_section_order(
    "ADLB-LBTEST",
    "ADLB-NEW_MICROCYTES",
    programs[["2_ADLB.R"]]
  )
  expect_section_order(
    c("ADLB-AVALC", "ADLB-LBTEST"),
    "ADLB-NEW_MACROCYTES",
    programs[["2_ADLB.R"]]
  )
  expect_section_order(
    "ADLB-NEW_MICROCYTES",
    "ADLB-NEW_MACROCYTES2",
    programs[["2_ADLB.R"]]
  )
  expect_section_order(
    c("ADLB-NEW_MICROCYTES", "ADLB-NEW_MACROCYTES"),
    "ADLB-NEW_MICROCYTES2_MACROCYTES2",
    programs[["2_ADLB.R"]]
  )
  expect_section_order(
    c("ADLB-LBTEST", "ADLB-NEW_MICROCYTES"),
    "ADLB-NEW_MICROCYTES2",
    programs[["2_ADLB.R"]]
  )
  expect_section_order(
    c("ADLB-AVAL", "ADLB-NEW_AVAL_01"),
    "ADLB-NEW_AVAL_02",
    programs[["2_ADLB.R"]]
  )
  expect_section_order(
    "ADLB-NEW_VISITNUM_01",
    "ADLB-NEW_VISITNUM_02",
    programs[["2_ADLB.R"]]
  )
  expect_section_order(
    "ADLB-LBTEST",
    "ADLB-NEW_PROTEIN",
    programs[["2_ADLB.R"]]
  )
  expect_section_order(
    "ADLB-LBTEST",
    "ADLB-NEW_SPECIFIC_GRAVITY",
    programs[["2_ADLB.R"]]
  )
  # Check ADLB table generated by program 2
  x[[2]] |> source()
  setDT(ADLB)
  setcolorder(ADLB, sort(names(ADLB)))
  data.table::setorder(ADLB, USUBJID, VISITNUM, LBSEQ, AVAL)
  attr(ADLB, "row.names") <- NULL
  ADLB |>
    data.table::setDF() |>
    expect_snapshot_value(style = "json2", variant = "adlb_1_ordered")

  # Check program 3: ADSL part 2
  expect_section_order(
    "ADSL-NEWFL02",
    "ADSL-NEWFL03-NEWREA03",
    programs[["3_ADSL.R"]]
  )

  # Check ADSL table generated by program 3
  x[[3]] |> source()
  setDT(ADSL)
  setcolorder(ADSL, sort(names(ADSL)))
  data.table::setorder(ADSL, USUBJID)
  attr(ADSL, "row.names") <- NULL

  ADSL |>
    data.table::setDF() |>
    expect_snapshot_value(style = "json2", variant = "adsl_2")
})
