#' Collate Primary Keys
#'
#' @description
#' Combines primary key information from _mighty.yml (via study@info) and ADaM
#' domain specifications. The _mighty.yml file contains keys for runtime datasets
#' (SDTM, metadata, and pre-existing ADaM). Domain specifications contain
#' keys for ADaM domains being generated by mighty.
#'
#' @param ui_yml List of ADaM domain specifications, each containing a `keys` element.
#' @param mighty_study_info List from study@info containing primary key information with
#'   `keys` element mapping domain names to key variables.
#'
#' @return
#' A list where each element is a named vector containing the primary keys
#' for that domain, combining runtime_keys from _mighty.yml and domain spec keys.
#' All domain names are converted to uppercase.
#'
#' @noRd
collate_primary_keys <- function(ui_yml, keys) {
  adam_keys <- lapply(ui_yml, \(domain_spec) domain_spec$keys) |>
    stats::setNames(toupper(names(ui_yml)))

  if (is.null(keys)) {
    return(adam_keys)
  }

  # Check for domains specified in both places
  names(keys) <- toupper(names(keys))
  duplicates <- intersect(names(adam_keys), names(keys))
  if (length(duplicates) > 0) {
    dup_list <- format_list(duplicates, format_domain)
    dup_msg <- paste0("The following domains appear in both: ", dup_list)

    throw_validation_error(
      category = "Duplicate domain keys",
      details = c(
        "Domains have keys defined in both {.file _mighty.yml} and domain specifications",
        "x" = dup_msg,
        "i" = "ADaM domains generated by mighty should only have keys in domain specs, not {.file _mighty.yml}"
      ),
      suggestions = c(
        "Remove key definitions from {.file _mighty.yml} for ADaM domains",
        "Keep key definitions in domain specification files",
        "Use {.file _mighty.yml} keys only for external domains (SDTM, etc.)"
      )
    )
  }

  c(keys, adam_keys)
}
