#' Collate Primary Keys
#'
#' @description
#' Combines primary key information from trial metadata and ADaM domain
#' specifications. Trial metadata contains keys for all datasets available
#' at runtime (SDTM, metadata, and pre-existing ADaM). Domain specifications
#' contain keys for ADaM domains being generated by mighty.
#'
#' @param ui_yml List of ADaM domain specifications, each containing a `keys` element.
#' @param trial_metadata_keys List containing primary key information with
#'   `keys` element mapping domain names to key variables.
#'
#' @return
#' A list where each element is a named vector containing the primary keys
#' for that domain, combining trial metadata keys and domain spec keys.
#'
#' @noRd
collate_primary_keys <- function(ui_yml, trial_metadata_keys) {
  # Extract ADaM keys from domain specifications (domains being generated)
  adam_keys <- lapply(ui_yml, \(domain_spec) domain_spec$keys)
  names(adam_keys) <- toupper(names(adam_keys))

  # Get keys from trial metadata (all runtime-available datasets)
  trial_keys <- trial_metadata_keys$keys
  if (!is.null(trial_keys)) {
    names(trial_keys) <- toupper(names(trial_keys))
  }

  # Check for domains specified in both places
  duplicates <- intersect(names(adam_keys), names(trial_keys))
  if (length(duplicates) > 0) {
    cli::cli_abort(c(
      "Domains have keys defined in both trial metadata and domain specifications",
      "x" = "The following domains appear in both: {.val {duplicates}}",
      "i" = "ADaM domains generated by mighty should only have keys in domain specs, not trial metadata"
    ))
  }

  # Combine keys from both sources
  c(trial_keys, adam_keys)
}
